# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BloodPressureMonitoring' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BloodPressureMonitoring

  pod 'SwiftCharts', '~> 0.6.1'
end
